version: '3'
services:
  db:
    container_name: db
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root

  web:
    container_name: web
    build: .
    command: rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/quuta
    ports:
      - "3000:3000"
    links:
      - db
